name: Test with issue lable
on:
  issues:
    types: [labeled]

jobs:
  job2:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    name: Check for issue label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the local file
        uses: ./
